baseURL = 'https://potatodiet.ca'
languageCode = 'en-us'
title = 'PotatoDiet'
assetDir = 'assets'
theme = 'book'
enableGitInfo = true

[params]
BookSection = '/'
BookRepo = 'https://github.com/potato-diet/potatodiet.ca'
BookDateFormat = '2 January 2006'
